from __future__ import annotations

from pathlib import Path
import shutil

import pytest

from queuely.job_processors import email_delivery, pdf_processing, report_generation
from queuely.job_processors.report_llm import StructuredReport
from queuely.services import cloudinary_storage


def _workspace_tmp(name: str) -> Path:
    path = Path("backend") / ".tmp_test_artifacts" / name
    if path.exists():
        shutil.rmtree(path)
    path.mkdir(parents=True, exist_ok=True)
    return path


def test_extract_pdf_content_from_text() -> None:
    payload = pdf_processing.parse_pdf_payload({"text": "page one\fpage two"})
    pages, metadata = pdf_processing.extract_pdf_content(payload)
    assert [page.text for page in pages] == ["page one", "page two"]
    assert metadata["source"] == "payload.text"


def test_pdf_payload_requires_single_source() -> None:
    with pytest.raises(Exception):
        pdf_processing.parse_pdf_payload({"text": "a", "pages": ["b"]})


def test_pdf_rejects_outside_allowed_roots() -> None:
    tmp_path = Path("C:/tmp/queuely-outside-root")
    if tmp_path.exists():
        shutil.rmtree(tmp_path)
    tmp_path.mkdir(parents=True, exist_ok=True)
    fake_pdf = tmp_path / "outside.pdf"
    fake_pdf.write_bytes(b"%PDF-1.4")
    payload = pdf_processing.parse_pdf_payload({"file_path": str(fake_pdf)})
    with pytest.raises(ValueError):
        pdf_processing.extract_pdf_content(payload)


def test_extract_pdf_content_from_cloudinary_url(monkeypatch) -> None:
    seen: dict[str, object] = {}

    def _download(url: str) -> bytes:
        seen["url"] = url
        return b"%PDF-1.4 fake-bytes"

    def _extract(pdf_path: Path, payload: pdf_processing.PdfProcessingPayload, *, source: str):
        seen["path"] = pdf_path
        seen["source"] = source
        seen["payload"] = payload
        return ([pdf_processing.PageExtraction(page_number=1, text="Cloudinary text", text_source="cloudinary", tables=[], used_ocr=False)], {"source": source})

    monkeypatch.setattr(pdf_processing, "download_url", _download)
    monkeypatch.setattr(pdf_processing, "_extract_pdf_pages_from_path", _extract)

    payload = pdf_processing.parse_pdf_payload({"cloudinary_url": "https://res.cloudinary.com/demo/raw/upload/sample.pdf"})
    pages, metadata = pdf_processing.extract_pdf_content(payload)

    assert pages[0].text == "Cloudinary text"
    assert metadata["source"] == "https://res.cloudinary.com/demo/raw/upload/sample.pdf"
    assert seen["url"] == "https://res.cloudinary.com/demo/raw/upload/sample.pdf"


def test_cloudinary_upload_helper_wraps_sdk(monkeypatch) -> None:
    monkeypatch.setattr(cloudinary_storage, "is_configured", lambda: True)
    monkeypatch.setattr(cloudinary_storage, "configure_cloudinary", lambda: None)
    monkeypatch.setattr(
        cloudinary_storage.cloudinary.uploader,
        "upload",
        lambda file, **options: {"public_id": "demo/public-id", "secure_url": "https://res.cloudinary.com/demo/raw/upload/sample.pdf", "bytes": 123, "format": "pdf"},
    )
    asset = cloudinary_storage.upload_bytes(b"pdf-bytes", filename="sample.pdf", folder="queuely/uploads", resource_type="raw")
    assert asset is not None
    assert asset.public_id == "demo/public-id"
    assert asset.secure_url.endswith("sample.pdf")


def test_generate_report_document_writes_markdown(monkeypatch) -> None:
    tmp_path = _workspace_tmp("report")
    monkeypatch.setattr(report_generation, "artifact_dir", lambda _kind: tmp_path)
    monkeypatch.setattr(report_generation, "emit_progress", lambda *args, **kwargs: None)
    result = report_generation.execute_report_job(
        "job-1234",
        {
            "title": "Weekly",
            "format": "md",
            "sections": [{"heading": "Summary", "body": "All systems nominal"}],
        },
    )
    output = tmp_path / "job-1234.md"
    assert output.exists()
    assert result["format"] == "md"
    assert result["section_count"] == 1


def test_report_generation_uses_llm_provider(monkeypatch) -> None:
    monkeypatch.setattr(report_generation, "emit_progress", lambda *args, **kwargs: None)
    monkeypatch.setattr(
        report_generation,
        "generate_structured_report",
        lambda **kwargs: StructuredReport(
            title="LLM Weekly",
            summary="Generated by provider",
            sections=[{"heading": "Summary", "body": "Provider output"}],
            metadata={"provider": kwargs["provider"]},
        ),
    )
    report = report_generation.build_structured_report(
        report_generation.parse_report_payload(
            {
                "title": "Weekly",
                "provider": "gemini",
                "sections": [{"heading": "Input", "body": "Raw section"}],
            },
            "job-9999",
        )
    )
    assert report.title == "LLM Weekly"
    assert report.metadata["provider"] == "gemini"


def test_build_email_message_sets_headers() -> None:
    payload = email_delivery.parse_email_payload(
        {
            "to": ["test@example.com"],
            "subject": "Hello",
            "body": "World",
            "reply_to": ["reply@example.com"],
            "cc": ["copy@example.com"],
        },
        "job-5678",
    )
    message = email_delivery.build_email_message(payload, "job-5678")
    assert message["To"] == "test@example.com"
    assert message["Reply-To"] == "reply@example.com"
    assert message["Cc"] == "copy@example.com"


def test_deliver_email_dry_run_writes_eml(monkeypatch) -> None:
    tmp_path = _workspace_tmp("email")
    monkeypatch.setattr(email_delivery, "artifact_dir", lambda _kind: tmp_path)
    monkeypatch.setattr(email_delivery, "emit_progress", lambda *args, **kwargs: None)
    result = email_delivery.execute_email_job(
        "job-5678",
        {"to": "test@example.com", "subject": "Hello", "body": "World", "dry_run": True},
    )
    output = tmp_path / "job-5678.eml"
    assert output.exists()
    assert result["delivery_mode"] == "dry_run"
    assert result["to"] == ["test@example.com"]
